# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Rel0adediso.Kvieta
PackageVersion: 6.4.0
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --elevated-install
  SilentWithProgress: --elevated-install
UpgradeBehavior: install
Commands:
- kvieta
ProductCode: '{3F9EED83-720B-4D5F-8E91-F1A9113CD812}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Rel0adediso/Kvieta-app/releases/download/kvieta-alpha-6.4/Kvieta-Setup-alpha-6.4.exe
  InstallerSha256: cc4a03eb610714233f81621c267e730ca7e6e5a8da62cbcd63bebbc7d1999628
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-09-27
